### ISSUE TITLE
Boxes of Frame 0 ist the same in all Animation / Hotkeys are still available when the filedialog is open

### ISSUE THREAD

**Issue by Zottelchen** [coelhucas/hitbox-editor#10]
Hi, 
it's me again! Found 2 (maybe 3) bugs:

1. When I add a (hurt)box to the 0-frame of my first animation it also appears on all the other animations on the 0-frame. Other frames seem to be fine.
![200823-145447822-QuietFrenchbulldog](https://user-images.githubusercontent.com/5148555/90978783-99e09c80-e550-11ea-90be-6d65fc3dcbe9.png)

2. When the filedialog is open, hotkeys are still available - so when your filename contains the letter **a**, you also add a new box in the background.

(3. There is also a lot of 
```
E 0:00:01.540   get_current_animation_position: Condition "!playback.current.from" is true. Returned: 0
  <C++->scene/animation/animation_player.cpp:1364 @ get_current_animation_position()
  <Stacktrace>  HitBoxManager.gd:78 @ _process()
```
spam in the console, but it doesn't cause a crash. It happens when a new animation is selected.)

Thank you again for this great tool 🤗

**Comment by coelhucas** [comment]
Hey, thanks for reporting! I'm going to take my time this weekend to solve these issues :)

**Comment by coelhucas** [comment]
Hey! I'm sorry for the late, things got a bit complicated and due to some personal stuff I just sent a PR fixing these and adding other minor improvements. Thanks for reporting! +1

I'm going to leave it opened for a while in case you have something else to say about these reported issues

**Comment by coelhucas** [comment]
Closing this. If you need anything else, feel free to report :)
